# Generated by Django 4.2.7 on 2026-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar américain ($)'), ('GBP', 'Livre sterling (£)'), ('LBP', 'Livre libanaise (ل.ل)')], default='EUR', max_length=3),
        ),
    ]
