# Generated by Django 4.2.7 on 2026-06-17 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_guestmember'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='guest_participants',
            field=models.ManyToManyField(blank=True, related_name='participated_expenses', to='groups.guestmember'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
