# Generated by Django 4.2.7 on 2026-06-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_guestmember'),
        ('expenses', '0002_expense_guest_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='guest_participants',
            field=models.ManyToManyField(blank=True, related_name='guest_participated_expenses', to='groups.guestmember'),
        ),
    ]
